repos:
- repo: git://github.com/dnephin/pre-commit-golang
  rev: fd0556d9a362a9a184327a4e8cf3c9f0dea3a47b
  hooks:
    - id: go-fmt
    - id: go-imports
    - id: golangci-lint
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy
